version: "3.9"

services:
  web:
    image: $IMAGE_TAG:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "80:30000"
    environment:
      - DB_PASSWORD=db_password
      - DB_USER=db_user
      - DB_NAME=db_name
      - FLASK_APP=run.py
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_user
      - POSTGRES_DB=db_name
